[package]
name = "aoc-frontend"
version = "0.2021.0"
authors = ["Dan F-M"]
edition = "2018"

[dependencies]
clap = "2.33.3"
reqwest = { version = "0.11.6", features = ["blocking"] }
aoc = { path = "../aoc" }
aoc-day01 = { path = "../days/day01" }
