name: adventofcode
version: 0.1.0.0
github: "dfm/adventofcode"
license: MIT
author: "Dan Foreman-Mackey"
maintainer: "foreman.mackey@gmail.com"
copyright: "2020, Dan Foreman-Mackey"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: "Haskell edition"
category: Coding
description: |
  Let's see how this goes

ghc-options:
  - -Wall
  - -Wcompat
  - -Wno-partial-type-signatures
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - split
  - bytestring
  - text
  - megaparsec
  - containers
  - sort

library:
  source-dirs: src

executables:
  day01:
    main: days/day01.hs
    dependencies:
      - adventofcode
  day02:
    main: days/day02.hs
    dependencies:
      - adventofcode
  day03:
    main: days/day03.hs
    dependencies:
      - adventofcode
  day04:
    main: days/day04.hs
    dependencies:
      - adventofcode
  day05:
    main: days/day05.hs
    dependencies:
      - adventofcode

tests:
  check:
    dependencies:
      - tasty >= 0.7
      - tasty-hunit
      - adventofcode
    source-dirs:
      - tests
    main: test.hs
