name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches:

jobs:
  test:
    name: Cargo ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - test --all
          - fmt --all -- --check
          - clippy -- -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache cargo directories
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: tests-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.command }}
          restore-keys: |
            tests-${{ hashFiles('**/Cargo.lock') }}-
            tests-
      - name: Run command
        run: cargo ${{ matrix.command }}
