name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches:

jobs:
  test:
    name: Cargo ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: []
        command: []
        include:
          - name: test
            command: test --all
          - name: fmt
            command: fmt --all -- --check
          - name: clippy
            command: clippy -- -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache cargo directories
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: tests-${{ matrix.name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            tests-${{ matrix.name }}-
            tests-
      - name: Run command
        run: cargo ${{ matrix.command }}
