name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: |
          cmake -B build .
          cmake --build build --parallel 2
      - name: Test
        run: ctest --output-on-failure --test-dir build
