name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Update rust toolchain"
        run: rustup update stable && rustup default stable
      - name: "Build"
        run: cargo build --verbose
      - name: "Test"
        run: cargo test --verbose
